version: '3.1'
services: 
  mysql:
    image: mysql:8.0.21
    platform: linux/x86_64
    container_name: container-mysql
    environment:
        - MYSQL_ROOT_PASSWORD=admin
    ports:
        - 3306:3306
    restart: 'always'
